spring:
  #main:
  #  web-application-type: none  # 必须禁用web应用类型
  #  banner-mode: off           # 禁用banner
  ai:
    mcp:
      server:
        #stdio: true            # 启用stdio模式
        name: vm-sexed-mcp-server # 服务器名称
        version: 0.0.1         # 服务器版本
  application:
    name: vm-mcp-server

server:
  port: 7388

logging:
  level:
    org.springframework.web.reactive.function.client: DEBUG